apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: sahaapp-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          env:
            - name: MONGO_URI
              value: "mongodb://mongodb:27017/SahaAppDB"
            - name: PORT
              value: "9000"
            - name: REDIS_URL
              value: "redis://redis:6379"
            - name: RABBITMQ_URL
              value: "amqp://rabbitmq:5672"
            - name: NODE_ENV
              value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    app: backend
